version: "3.9"

services:
  fastapi-app:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    container_name: fastapi-app-dev
    ports:
      - "5001:5001"
    environment:
      - LOKI_ENDPOINT=        # 기본은 비활성(빈 값)
    volumes:
      - ./fastapi-app:/app    # 코드 수정 반영(개발용)
    networks: [app-net]

networks:
  app-net:
    driver: bridge
